# A standard setup, specifying model architecture, training parameters,
# and evaluation of the trained model
!Experiment # 'standard' is the name given to the experiment
  name: first_xnmt_sum_to_en # every experiment needs a name
  # global parameters shared throughout the experiment
  exp_global: !ExpGlobal
    # {EXP_DIR} is a placeholder for the directory in which the config file lies.
    # {EXP} is a placeholder for the experiment name (here: 'standard')
    model_file: 'sumerian_to_en.mod'
    log_file: 'sumerian_to_en.log'
    default_layer_dim: 512
    dropout: 0.3
  # model architecture
  model: !DefaultTranslator
    src_reader: !PlainTextReader
      vocab: !Vocab {vocab_file: ../sp_encodings/sumerian.vocab}
    trg_reader: !PlainTextReader
      vocab: !Vocab {vocab_file: ../sp_encodings/en.wiki.bpe.vs5000.vocab}
    src_embedder: !SimpleWordEmbedder
      emb_dim: 512
    encoder: !BiLSTMSeqTransducer
      layers: 1
    attender: !MlpAttender
      hidden_dim: 512
      state_dim: 512
      input_dim: 512
    decoder: !AutoRegressiveDecoder
      embedder: !SimpleWordEmbedder
        emb_dim: 512
      rnn: !UniLSTMSeqTransducer
        layers: 1
      transform: !AuxNonLinear
        output_dim: 512
        activation: 'tanh'
      bridge: !CopyBridge {}
      scorer: !Softmax {}
    inference: !AutoRegressiveInference
      search_strategy: !BeamSearch
        beam_size: 5
  # training parameters
  train: !SimpleTrainingRegimen
    batcher: !SrcBatcher
      batch_size: 32
    trainer: !AdamTrainer
      alpha: 0.001
    run_for_epochs: 2
    src_file: ../language_pairs/sumerian.txt
    trg_file: ../language_pairs/translated_sumerian.txt
    dev_tasks:
      - !LossEvalTask
        src_file: ../language_pairs/sumerian.txt
        ref_file: ../language_pairs/translated_sumerian.txt
  # final evaluation
  evaluate:
    - !AccuracyEvalTask
      eval_metrics: bleu
      src_file: ../language_pairs/sumerian.txt
      ref_file: ../language_pairs/translated_sumerian.txt
      hyp_file: examples/output/{EXP}.test_hyp